version: '3.8'

services:
  jetchat:
    image: postgres:latest
    container_name: jetchat
    restart: always
    environment:
      POSTGRES_DB: jetchat
      POSTGRES_USER: jetchatuser
      POSTGRES_PASSWORD: jetchatpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - jetchat

volumes:
  postgres_data: