# Generated by Django 4.2 on 2025-08-01 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='viewd_at',
            new_name='viewed_at',
        ),
    ]
